In [7]:

import requests
import urllib3
import csv
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
from bs4 import BeautifulSoup

Output = pd.DataFrame()

for i in range(320256,330260):
    Data = {}
    s = random.randrange(2,5)
    time.sleep(s)
    URL = 'https://lankapropertyweb.com/sale/property_details-'+str(i)+'.html'
    print(URL)
    r = requests.get(URL)
    Data['URLnumber'] = str(i)
    soup = BeautifulSoup(r.content,'html.parser')
    records = soup.find_all('div',class_= 'col-md-7 col-md-offset-1')
    if records:
        ##########Price of the property##########
        price =soup.find('div',class_='price-detail')
        got= price.text.split()
#       print(got)
        for x in range(len(got)):
            Data['Price']=got[1]+' Rs'
            
        ##########Locality##########    
        location=soup.find('span',class_='details-location')   
        locationDetail=location.text.split()
        for x in range(len(locationDetail)):
            if locationDetail[x]=='Colombo':
                Data['Location']= 'Colombo '+ locationDetail[x+1]
        
        ########## Property Details ##########         
        details =soup.find('div',class_='col-lg-12 important green-borders')
        gotdetail = details.text.split()
        for x in range(len(gotdetail)):
#           print(gotdetail)
            ##########Type of property##########
            if gotdetail[x]=='Apartment':
                Data['Type']='Apartment'
            elif gotdetail[x]=='House':
                Data['Type']='Land House' 
           
            ##########Number of Bedrooms##########
            if gotdetail[x]=='Bedrooms:':
                Data['Bedrooms']=gotdetail[x+1]
                
            ##########Number of Bathrooms##########
            if gotdetail[x]=='Bathrooms/WCs:':
                Data['Bathrooms']=gotdetail[x+1]
                
            ##########Number of Bathrooms##########
            if gotdetail[x]=='area:':
                Data['Floor area']= gotdetail[x+1]
                
            ##########Parkings##########
            if gotdetail[x]=='Car':
                Data['Parkings']=gotdetail[x+3]
                
            ##########Availability##########
            if gotdetail[x]=='Available':
                Data['Availability'] = 'Ready to move'
                
        features=soup.find('div',class_='details-features')
        gotfeature=features.text.split()
        for y in range(len(gotfeature)):
#             print(gotfeature)
            
            ##########Swimming pool##########
            if gotfeature[y]=='SWIMMING':
                Data['Swimming pool']='Yes'
            else:
                Data['Swimming pool']='No'
                
            ########## Furnishing ##########
            if gotfeature[y]=='FULLY':
                Data['Furnishing']='Fully furnished'
            else:
                Data['Furnishing']='UnFurnished'
                
            ##########State of the property##########
            if gotfeature[y]=='BRAND':
                Data['State']='New'
            else:
                Data['State']='Resale'
                

    Output = Output.append(Data,ignore_index=True)
    
    print(r.status_code)

https://lankapropertyweb.com/sale/property_details-330254.html
200
https://lankapropertyweb.com/sale/property_details-330255.html
200
https://lankapropertyweb.com/sale/property_details-330256.html
200
https://lankapropertyweb.com/sale/property_details-330257.html
200
https://lankapropertyweb.com/sale/property_details-330258.html
200
https://lankapropertyweb.com/sale/property_details-330259.html
200

In [8]:
Output

,Bathrooms,Bedrooms,Floor area,Furnishing,Location,Parkings,Price,State,Swimming pool,Type,URLnumber,Availability
0,2,2,890,UnFurnished,Colombo 4,1,"26,500,000 Rs",Resale,No,Apartment,330254,NaN
1,4,4,3700,UnFurnished,NaN,4,"42,000,000 Rs",Resale,No,Land House,330255,Ready to move
2,2,4,1500,UnFurnished,NaN,1,"12,700,000 Rs",Resale,No,Land House,330256,Ready to move
3,Floor,above,No.,UnFurnished,NaN,Age,"50,000 Rs",Resale,No,Land House,330257,Ready to move
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,330258,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,330259,NaN

In [9]:
Output.to_csv('fypfinal12.csv')